<a href="https://colab.research.google.com/github/hadiah115-tech/code-switching-codesaviours-si26-hadia/blob/main/SI26_Week6_hadia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd

print("Project 2 Started")

Project 2 Started

In [29]:
import pandas as pd

# 150 Annotated Code-Switched Sentences (Roman Urdu + English)
data = [
    # 1 to 10
    {"sentence": "Aaj ka din bohot busy tha", "words": ["Aaj", "ka", "din", "bohot", "busy", "tha"], "labels": ["URD", "URD", "URD", "URD", "ENG", "URD"]},
    {"sentence": "Yaar seriously I can not even right now", "words": ["Yaar", "seriously", "I", "can", "not", "even", "right", "now"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai kal mera presentation hai still not prepared", "words": ["Bhai", "kal", "mera", "presentation", "hai", "still", "not", "prepared"], "labels": ["URD", "URD", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Khana kha liya I was literally waiting for you", "words": ["Khana", "kha", "liya", "I", "was", "literally", "waiting", "for", "you"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj mera mood nahi hai for anything", "words": ["Aaj", "mera", "mood", "nahi", "hai", "for", "anything"], "labels": ["URD", "URD", "ENG", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Main raste mein hoon please wait for ten minutes", "words": ["Main", "raste", "mein", "hoon", "please", "wait", "for", "ten", "minutes"], "labels": ["URD", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is weather mein aik hot cup of chai is mandatory", "words": ["Is", "weather", "mein", "aik", "hot", "cup", "of", "chai", "is", "mandatory"], "labels": ["URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG"]},
    {"sentence": "Assignment submit kar di hai or still working on it", "words": ["Assignment", "submit", "kar", "di", "hai", "or", "still", "working", "on", "it"], "labels": ["ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal ki meeting ka time reschedule ho gaya hai", "words": ["Kal", "ki", "meeting", "ka", "time", "reschedule", "ho", "gaya", "hai"], "labels": ["URD", "URD", "ENG", "URD", "ENG", "ENG", "URD", "URD", "URD"]},
    {"sentence": "Bohot traffic tha so I missed the first lecture", "words": ["Bohot", "traffic", "tha", "so", "I", "missed", "the", "first", "lecture"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},

    # 11 to 20
    {"sentence": "Mujhe yeh movie dekhni hai looks very interesting", "words": ["Mujhe", "yeh", "movie", "dekhni", "hai", "looks", "very", "interesting"], "labels": ["URD", "URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Please pass me that water bottle bohot pyas lagi hai", "words": ["Please", "pass", "me", "that", "water", "bottle", "bohot", "pyas", "lagi", "hai"], "labels": ["ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "URD", "URD", "URD", "URD"]},
    {"sentence": "Itna tension mat lo everything will be fine", "words": ["Itna", "tension", "mat", "lo", "everything", "will", "be", "fine"], "labels": ["URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Laptop hang ho gaya hai I need to restart it", "words": ["Laptop", "hang", "ho", "gaya", "hai", "I", "need", "to", "restart", "it"], "labels": ["ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh wala design looks aesthetic and modern", "words": ["Yeh", "wala", "design", "looks", "aesthetic", "and", "modern"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Suno message check karo I sent you the file", "words": ["Suno", "message", "check", "karo", "I", "sent", "you", "the", "file"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "It is so hot today bilkul bahar nikalne ka dil nahi kar raha", "words": ["It", "is", "so", "hot", "today", "bilkul", "bahar", "nikalne", "ka", "dil", "nahi", "kar", "raha"], "labels": ["ENG", "ENG", "ENG", "ENG", "ENG", "URD", "URD", "URD", "URD", "URD", "URD", "URD", "URD"]},
    {"sentence": "Is code mein bug hai can you help me debug it", "words": ["Is", "code", "mein", "bug", "hai", "can", "you", "help", "me", "debug", "it"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Chai break ka time ho gaya hai let us go outside", "words": ["Chai", "break", "ka", "time", "ho", "gaya", "hai", "let", "us", "go", "outside"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Main kal shopping par ja rahi hoon with my sister", "words": ["Main", "kal", "shopping", "par", "ja", "rahi", "hoon", "with", "my", "sister"], "labels": ["URD", "URD", "ENG", "URD", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},

    # 21 to 30
    {"sentence": "Project ki deadline extend ho gayi hai what a relief", "words": ["Project", "ki", "deadline", "extend", "ho", "gayi", "hai", "what", "a", "relief"], "labels": ["ENG", "URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera phone charge nahi ho raha check the cable", "words": ["Mera", "phone", "charge", "nahi", "ho", "raha", "check", "the", "cable"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai this place serves the best biryani in town", "words": ["Bhai", "this", "place", "serves", "the", "best", "biryani", "in", "town"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "URD", "ENG", "ENG"]},
    {"sentence": "Tumhara idea bohot brilliant tha I loved it", "words": ["Tumhara", "idea", "bohot", "brilliant", "tha", "I", "loved", "it"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "WiFi slow chal raha hai try reconnecting it", "words": ["WiFi", "slow", "chal", "raha", "hai", "try", "reconnecting", "it"], "labels": ["ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap late kyun ho gaye the traffic was terrible", "words": ["Aap", "late", "kyun", "ho", "gaye", "the", "traffic", "was", "terrible"], "labels": ["URD", "ENG", "URD", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj raat ko online match khelein ge match starts at nine", "words": ["Aaj", "raat", "ko", "online", "match", "khelein", "ge", "match", "starts", "at", "nine"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera exam bohot tough tha overall score bad aayega", "words": ["Mera", "exam", "bohot", "tough", "tha", "overall", "score", "bad", "aayega"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "URD"]},
    {"sentence": "Bahar mausam bohot awesome hai let us go for a drive", "words": ["Bahar", "mausam", "bohot", "awesome", "hai", "let", "us", "go", "for", "a", "drive"], "labels": ["URD", "URD", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is issue ka solution clear nahi hai need more research", "words": ["Is", "issue", "ka", "solution", "clear", "nahi", "hai", "need", "more", "research"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},

    # 31 to 40
    {"sentence": "Bhai mujhe yeh shirt buy karni hai looks high quality", "words": ["Bhai", "mujhe", "yeh", "shirt", "buy", "karni", "hai", "looks", "high", "quality"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ne mera message ignore kar diya why are you upset", "words": ["Aap", "ne", "mera", "message", "ignore", "kar", "diya", "why", "are", "you", "upset"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal subah early morning gym jana hai so sleep early", "words": ["Kal", "subah", "early", "morning", "gym", "jana", "hai", "so", "sleep", "early"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh song bohot catchy hai playing on loop", "words": ["Yeh", "song", "bohot", "catchy", "hai", "playing", "on", "loop"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Unka customer support is hopeless response nahi deta", "words": ["Unka", "customer", "support", "is", "hopeless", "response", "nahi", "deta"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "URD", "URD"]},
    {"sentence": "Mujhe naya phone lena hai suggestion do fast", "words": ["Mujhe", "naya", "phone", "lena", "hai", "suggestion", "do", "fast"], "labels": ["URD", "URD", "ENG", "URD", "URD", "ENG", "URD", "ENG"]},
    {"sentence": "Is resturant ki service super slow thi delay script ho gaya", "words": ["Is", "resturant", "ki", "service", "super", "slow", "thi", "delay", "script", "ho", "gaya"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "URD", "URD"]},
    {"sentence": "Kal mera result aane wala hai feeling so nervous", "words": ["Kal", "mera", "result", "aane", "wala", "hai", "feeling", "so", "nervous"], "labels": ["URD", "URD", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Gari mein fuel khatam hone wala hai find nearest station", "words": ["Gari", "mein", "fuel", "khatam", "hone", "wala", "hai", "find", "nearest", "station"], "labels": ["URD", "URD", "ENG", "URD", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Main aap se later contact karta hoon currently in meeting", "words": ["Main", "aap", "se", "later", "contact", "karta", "hoon", "currently", "in", "meeting"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},

    # 41 to 50
    {"sentence": "Yaar tension na lo God will fix everything soon", "words": ["Yaar", "tension", "na", "lo", "God", "will", "fix", "everything", "soon"], "labels": ["URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh color combination looks weird change it please", "words": ["Yeh", "color", "combination", "looks", "weird", "change", "it", "please"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera order deliver nahi hua order status is pending", "words": ["Mera", "order", "deliver", "nahi", "hua", "order", "status", "is", "pending"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Tumhara presentation style bohot impressive tha keep it up", "words": ["Tumhara", "presentation", "style", "bohot", "impressive", "tha", "keep", "it", "up"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Khaana bohot spicy tha my mouth is burning", "words": ["Khaana", "bohot", "spicy", "tha", "my", "mouth", "is", "burning"], "labels": ["URD", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ne location send ki hai I am following map", "words": ["Aap", "ne", "location", "send", "ki", "hai", "I", "am", "following", "map"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh project team effort tha everyone worked hard", "words": ["Yeh", "project", "team", "effort", "tha", "everyone", "worked", "hard"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Main ne insta story post kar di check it out", "words": ["Main", "ne", "insta", "story", "post", "kar", "di", "check", "it", "out"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Is saal thand bohot zyada hai weather is freezing", "words": ["Is", "saal", "thand", "bohot", "zyada", "hai", "weather", "is", "freezing"], "labels": ["URD", "URD", "URD", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera subscription expire ho gaya hai need to renew", "words": ["Mera", "subscription", "expire", "ho", "gaya", "hai", "need", "to", "renew"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},

    # 51 to 60
    {"sentence": "Aap ka resume shortlisted ho gaya hai expect a call", "words": ["Aap", "ka", "resume", "shortlisted", "ho", "gaya", "hai", "expect", "a", "call"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh coffee bohot strong hai my brain woke up", "words": ["Yeh", "coffee", "bohot", "strong", "hai", "my", "brain", "woke", "up"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai drive carefully road par hazard hai", "words": ["Bhai", "drive", "carefully", "road", "par", "hazard", "hai"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "URD"]},
    {"sentence": "Main ne update install kar liya hai app is smooth now", "words": ["Main", "ne", "update", "install", "kar", "liya", "hai", "app", "is", "smooth", "now"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj raat dinner bahar se order karte hain tired of cooking", "words": ["Aaj", "raat", "dinner", "bahar", "se", "order", "karte", "hain", "tired", "of", "cooking"], "labels": ["URD", "URD", "ENG", "URD", "URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh dialogue bohot iconic tha crowd went wild", "words": ["Yeh", "dialogue", "bohot", "iconic", "tha", "crowd", "went", "wild"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Apna password share mat karna security breach ho jaye ga", "words": ["Apna", "password", "share", "mat", "karna", "security", "breach", "ho", "jaye", "ga"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "URD", "URD", "URD"]},
    {"sentence": "Aaj mera workout skipp ho gaya feel so guilty", "words": ["Aaj", "mera", "workout", "skipp", "ho", "gaya", "feel", "so", "guilty"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Is laptop ki battery timing amazing hai lasts all day", "words": ["Is", "laptop", "ki", "battery", "timing", "amazing", "hai", "lasts", "all", "day"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera schedule bohot packed hai cannot fit another task", "words": ["Mera", "schedule", "bohot", "packed", "hai", "cannot", "fit", "another", "task"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},

    # 61 to 70
    {"sentence": "Bhai suno email verify karo code message aya hoga", "words": ["Bhai", "suno", "email", "verify", "karo", "code", "message", "aya", "hoga"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "URD", "URD"]},
    {"sentence": "Yeh camera clarity is insane picture looks real", "words": ["Yeh", "camera", "clarity", "is", "insane", "picture", "looks", "real"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Main parson karachi ja raha hoon booking complete", "words": ["Main", "parson", "karachi", "ja", "rahi", "hoon", "booking", "complete"], "labels": ["URD", "URD", "URD", "URD", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Is hotel ka ambiance is so aesthetic and clean", "words": ["Is", "hotel", "ka", "ambiance", "is", "so", "aesthetic", "and", "clean"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera exam center bohot door tha reached just in time", "words": ["Mera", "exam", "center", "bohot", "door", "tha", "reached", "just", "in", "time"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh mobile app crash kar rahi hai reinstall it again", "words": ["Yeh", "mobile", "app", "crash", "kar", "rahi", "hai", "reinstall", "it", "again"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mujhe naya laptop lena hai budget is limited", "words": ["Mujhe", "naya", "laptop", "lena", "hai", "budget", "is", "limited"], "labels": ["URD", "URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai link copy karke send kar do quickly", "words": ["Bhai", "link", "copy", "karke", "send", "kar", "do", "quickly"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "URD", "URD", "ENG"]},
    {"sentence": "Unki customer service is very supportive issue resolved instantly", "words": ["Unki", "customer", "service", "is", "very", "supportive", "issue", "resolved", "instantly"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera mic mute tha I was speaking for five minutes", "words": ["Mera", "mic", "mute", "tha", "I", "was", "speaking", "for", "five", "minutes"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},

    # 71 to 80
    {"sentence": "Aaj shaam ko tea party hai join us guys", "words": ["Aaj", "shaam", "ko", "tea", "party", "hai", "join", "us", "guys"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh movie trailer was mindblowing must watch film", "words": ["Yeh", "movie", "trailer", "was", "mindblowing", "must", "watch", "film"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Main kal shopping mall gaya tha bought a cool jacket", "words": ["Main", "kal", "shopping", "mall", "gaya", "tha", "bought", "a", "cool", "jacket"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai screen share karo let me view your error", "words": ["Bhai", "screen", "share", "karo", "let", "me", "view", "your", "error"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh topic bohot confusing hai need simple explanation", "words": ["Yeh", "topic", "bohot", "confusing", "hai", "need", "simple", "explanation"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mujhe thori sleep chahiye tired after long drive", "words": ["Mujhe", "thori", "sleep", "chahiye", "tired", "after", "long", "drive"], "labels": ["URD", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is phone ka display is super crisp colors look vibrant", "words": ["Is", "phone", "ka", "display", "is", "super", "crisp", "colors", "look", "vibrant"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj mera workout session peak tha hit new personal record", "words": ["Aaj", "mera", "workout", "session", "peak", "tha", "hit", "new", "personal", "record"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera account block ho gaya logging in was failed", "words": ["Mera", "account", "block", "ho", "gaya", "logging", "in", "was", "failed"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal fast food khaya tha feeling bloated right now", "words": ["Kal", "fast", "food", "khaya", "tha", "feeling", "bloated", "right", "now"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},

    # 81 to 90
    {"sentence": "Bhai playlist change karo play some upbeat tracks", "words": ["Bhai", "playlist", "change", "karo", "play", "some", "upbeat", "tracks"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ka delivery location is out of range change address", "words": ["Aap", "ka", "delivery", "location", "is", "out", "of", "range", "change", "address"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh speaker sound quality is amazing worth every penny", "words": ["Yeh", "speaker", "sound", "quality", "is", "amazing", "worth", "every", "penny"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Main ne new project launch kar diya feeling proud", "words": ["Main", "ne", "new", "project", "launch", "kar", "diya", "feeling", "proud"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Bhai bill divide kar lete hain equal split for everyone", "words": ["Bhai", "bill", "divide", "kar", "lete", "hain", "equal", "split", "for", "everyone"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh place Instagrammable hai photo session zaroori hai", "words": ["Yeh", "place", "Instagrammable", "hai", "photo", "session", "zaroori", "hai"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "ENG", "URD", "URD"]},
    {"sentence": "Mera brain freeze ho gaya processing speed slow hai", "words": ["Mera", "brain", "freeze", "ho", "gaya", "processing", "speed", "slow", "hai"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "URD"]},
    {"sentence": "Aaj raat match stream hoga let us watch live together", "words": ["Aaj", "raat", "match", "stream", "hoga", "let", "us", "watch", "live", "together"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ki post viral ho gayi got thousand views", "words": ["Aap", "ki", "post", "viral", "ho", "gayi", "got", "thousand", "views"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mujhe shortcut pata hai we will reach quickly", "words": ["Mujhe", "shortcut", "pata", "hai", "we", "will", "reach", "quickly"], "labels": ["URD", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},

    # 91 to 100
    {"sentence": "Is laptop ki RAM upgrade karni paray gi system laggy hai", "words": ["Is", "laptop", "ki", "RAM", "upgrade", "karni", "paray", "gi", "system", "laggy", "hai"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "URD"]},
    {"sentence": "Bhai car parking full hai search another spot", "words": ["Bhai", "car", "parking", "full", "hai", "search", "another", "spot"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh ice cream flavor is top notch so creamy", "words": ["Yeh", "ice", "cream", "flavor", "is", "top", "notch", "so", "creamy"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera presentation slide deck is complete review it once", "words": ["Mera", "presentation", "slide", "deck", "is", "complete", "review", "it", "once"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj office mein party thi full fun atmosphere", "words": ["Aaj", "office", "mein", "party", "thi", "full", "fun", "atmosphere"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Main ticket cancel kar raha hoon plan postponed indefinitely", "words": ["Main", "ticket", "cancel", "kar", "raha", "hoon", "plan", "postponed", "indefinitely"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Is game graphics are unreal looks like real life", "words": ["Is", "game", "graphics", "are", "unreal", "looks", "like", "real", "life"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ne invoice clear kar diya update payment status", "words": ["Aap", "ne", "invoice", "clear", "kar", "diya", "update", "payment", "status"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh dress size is too tight replace with larger size", "words": ["Yeh", "dress", "size", "is", "too", "tight", "replace", "with", "larger", "size"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai backup file create kar lo safety measure", "words": ["Bhai", "backup", "file", "create", "kar", "lo", "safety", "measure"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG"]},

    # 101 to 110
    {"sentence": "Aaj mausam clear hai blue sky visible everywhere", "words": ["Aaj", "mausam", "clear", "hai", "blue", "sky", "visible", "everywhere"], "labels": ["URD", "URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera phone drop ho gaya screen shattered completely", "words": ["Mera", "phone", "drop", "ho", "gaya", "screen", "shattered", "completely"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai discount deal active hai grab it fast", "words": ["Bhai", "discount", "deal", "active", "hai", "grab", "it", "fast"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Is book ki summary btao main idea kya hai", "words": ["Is", "book", "ki", "summary", "btao", "main", "idea", "kya", "hai"], "labels": ["URD", "ENG", "URD", "ENG", "URD", "ENG", "ENG", "URD", "URD"]},
    {"sentence": "Main ne email draft kar li sends after review", "words": ["Main", "ne", "email", "draft", "kar", "li", "sends", "after", "review"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh café ka environment is super chill highly recommended", "words": ["Yeh", "café", "ka", "environment", "is", "super", "chill", "highly", "recommended"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera code execute nahi ho raha throws null pointer exception", "words": ["Mera", "code", "execute", "nahi", "ho", "raha", "throws", "null", "pointer", "exception"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal hum mountain trip par ja rahey feel super excited", "words": ["Kal", "hum", "mountain", "trip", "par", "ja", "rahey", "feel", "super", "excited"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Unka startup pitch was super impressive investors approved funding", "words": ["Unka", "startup", "pitch", "was", "super", "impressive", "investors", "approved", "funding"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai keyboard keys are jammed fix it properly", "words": ["Bhai", "keyboard", "keys", "are", "jammed", "fix", "it", "properly"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},

    # 111 to 120
    {"sentence": "Aaj mera gaming marathon hai playing with squad tonight", "words": ["Aaj", "mera", "gaming", "marathon", "hai", "playing", "with", "squad", "tonight"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is laptop ki cooling fan makes loud noise check internal fan", "words": ["Is", "laptop", "ki", "cooling", "fan", "makes", "loud", "noise", "check", "internal", "fan"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ka parcel dispatched ho gaya track package online", "words": ["Aap", "ka", "parcel", "dispatched", "ho", "gaya", "track", "package", "online"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Main ne form submit kar diya waiting for confirmation email", "words": ["Main", "ne", "form", "submit", "kar", "diya", "waiting", "for", "confirmation", "email"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh song bass drop is crazy heavy sound quality", "words": ["Yeh", "song", "bass", "drop", "is", "crazy", "heavy", "sound", "quality"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai location live share kar do finding destination hard", "words": ["Bhai", "location", "live", "share", "kar", "do", "finding", "destination", "hard"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera battery saver on hai screen brightness low karo", "words": ["Mera", "battery", "saver", "on", "hai", "screen", "brightness", "low", "karo"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "URD"]},
    {"sentence": "Aaj hum new strategy discuss karein ge team alignment crucial", "words": ["Aaj", "hum", "new", "strategy", "discuss", "karein", "ge", "team", "alignment", "crucial"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Is mobile ka processor is very fast zero lag experienced", "words": ["Is", "mobile", "ka", "processor", "is", "very", "fast", "zero", "lag", "experienced"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal mera interview scheduled hai preparing answer notes", "words": ["Kal", "mera", "interview", "scheduled", "hai", "preparing", "answer", "notes"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},

    # 121 to 130
    {"sentence": "Bhai wifi speed slow aarahey hai restart router now", "words": ["Bhai", "wifi", "speed", "slow", "aarahey", "hai", "restart", "router", "now"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh online course is super practical skills gained easily", "words": ["Yeh", "online", "course", "is", "super", "practical", "skills", "gained", "easily"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Main shaam ko walk par jaata hoon keeping healthy routine", "words": ["Main", "shaam", "ko", "walk", "par", "jaata", "hoon", "keeping", "healthy", "routine"], "labels": ["URD", "URD", "URD", "ENG", "URD", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Unka product design is modern customer loved interface", "words": ["Unka", "product", "design", "is", "modern", "customer", "loved", "interface"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai seat reserve kar lo hall is getting crowded", "words": ["Bhai", "seat", "reserve", "kar", "lo", "hall", "is", "getting", "crowded"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is phone ki battery drain quick ho rahi optimization required", "words": ["Is", "phone", "ki", "battery", "drain", "quick", "ho", "rahi", "optimization", "required"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Aaj raat hum BBQ party karein ge inviting all friends", "words": ["Aaj", "raat", "hum", "BBQ", "party", "karein", "ge", "inviting", "all", "friends"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera laptop charger damage ho gaya buy new adapter", "words": ["Mera", "laptop", "charger", "damage", "ho", "gaya", "buy", "new", "adapter"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh movie climax was shocking totally unexpected plot twist", "words": ["Yeh", "movie", "climax", "was", "shocking", "totally", "unexpected", "plot", "twist"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Aap ne notification clear kar di check inbox again", "words": ["Aap", "ne", "notification", "clear", "kar", "di", "check", "inbox", "again"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},

    # 131 to 140
    {"sentence": "Bhai dark mode enable karo screen is too bright", "words": ["Bhai", "dark", "mode", "enable", "karo", "screen", "is", "too", "bright"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is game mein graphic glitch hai need software patch", "words": ["Is", "game", "mein", "graphic", "glitch", "hai", "need", "software", "patch"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Main ne flight tickets book kar leen trip confirmed", "words": ["Main", "ne", "flight", "tickets", "book", "kar", "leen", "trip", "confirmed"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Yeh pizza topping is delicious extra cheese added", "words": ["Yeh", "pizza", "topping", "is", "delicious", "extra", "cheese", "added"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai audio volume high karo cannot hear sound", "words": ["Bhai", "audio", "volume", "high", "karo", "cannot", "hear", "sound"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera server down ho gaya website not responding", "words": ["Mera", "server", "down", "ho", "gaya", "website", "not", "responding"], "labels": ["URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj main ne goal complete kar liya feeling victorious", "words": ["Aaj", "main", "ne", "goal", "complete", "kar", "liya", "feeling", "victorious"], "labels": ["URD", "URD", "URD", "ENG", "ENG", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Is camera ka portrait mode is aesthetic background blurry", "words": ["Is", "camera", "ka", "portrait", "mode", "is", "aesthetic", "background", "blurry"], "labels": ["URD", "ENG", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal mera final exam hai study mode activated", "words": ["Kal", "mera", "final", "exam", "hai", "study", "mode", "activated"], "labels": ["URD", "URD", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai file zip karke mail kar do easy download", "words": ["Bhai", "file", "zip", "karke", "mail", "kar", "do", "easy", "download"], "labels": ["URD", "ENG", "ENG", "URD", "ENG", "URD", "URD", "ENG", "ENG"]},

    # 141 to 150
    {"sentence": "Yeh shoes quality is premium very comfortable walk", "words": ["Yeh", "shoes", "quality", "is", "premium", "very", "comfortable", "walk"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Main ne feedback form fill kar diya submitted successfully", "words": ["Main", "ne", "feedback", "form", "fill", "kar", "diya", "submitted", "successfully"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG"]},
    {"sentence": "Unka marketing campaign went viral high conversion rate", "words": ["Unka", "marketing", "campaign", "went", "viral", "high", "conversion", "rate"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai app permissions allow karo camera access required", "words": ["Bhai", "app", "permissions", "allow", "karo", "camera", "access", "required"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Mera storage memory full ho gayi clean junk files", "words": ["Mera", "storage", "memory", "full", "ho", "gayi", "clean", "junk", "files"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Aaj weather condition is stormy stay indoor guys", "words": ["Aaj", "weather", "condition", "is", "stormy", "stay", "indoor", "guys"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Is laptop touchpad is super smooth gestures work fast", "words": ["Is", "laptop", "touchpad", "is", "super", "smooth", "gestures", "work", "fast"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Kal mera flight timing is early morning alarm set", "words": ["Kal", "mera", "flight", "timing", "is", "early", "morning", "alarm", "set"], "labels": ["URD", "URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]},
    {"sentence": "Bhai social media detox zaroori hai taking offline break", "words": ["Bhai", "social", "media", "detox", "zaroori", "hai", "taking", "offline", "break"], "labels": ["URD", "ENG", "ENG", "ENG", "URD", "URD", "ENG", "ENG", "ENG"]},
    {"sentence": "Yeh software license is active status green color", "words": ["Yeh", "software", "license", "is", "active", "status", "green", "color"], "labels": ["URD", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG", "ENG"]}
]

# Convert nested structure into flat CSV DataFrame
rows = []
for entry in data:
    for word, label in zip(entry['words'], entry['labels']):
        rows.append({
            'sentence': entry['sentence'],
            'word': word,
            'label': label
        })

df = pd.DataFrame(rows)

# Save to CSV file
df.to_csv('dataset.csv', index=False, encoding='utf-8')

# Output Statistics
print("--------------------------------------------------")
print(f"SUCCESS! Dataset Created: {len(df)} word entries.")
print(f"Total Unique Sentences: {df.sentence.nunique()}")
print("--------------------------------------------------")
print("Label Distribution:")
print(df.label.value_counts())
print("--------------------------------------------------")

--------------------------------------------------
SUCCESS! Dataset Created: 1358 word entries.
Total Unique Sentences: 150
--------------------------------------------------
Label Distribution:
label
ENG    868
URD    490
Name: count, dtype: int64
--------------------------------------------------

In [21]:
import pandas as pd

print("Code Saviours SI-26")
print("Project 2 - Code Switching Dataset")

Code Saviours SI-26
Project 2 - Code Switching Dataset

In [22]:
df = pd.read_csv("dataset.csv")

df.head()

                    sentence   word label
0  Aaj ka din bohot busy tha    Aaj   URD
1  Aaj ka din bohot busy tha     ka   URD
2  Aaj ka din bohot busy tha    din   URD
3  Aaj ka din bohot busy tha  bohot   URD
4  Aaj ka din bohot busy tha   busy   ENG

In [23]:
print("Total Word Entries:", len(df))

Total Word Entries: 1358

In [24]:
print("Total Sentences:", df["sentence"].nunique())

Total Sentences: 150

In [25]:
print("Label Distribution")
print(df["label"].value_counts())

Label Distribution
label
ENG    868
URD    490
Name: count, dtype: int64

In [26]:
df.sample(10)

                                               sentence       word label
215         Tumhara idea bohot brilliant tha I loved it          I   ENG
738   Bhai playlist change karo play some upbeat tracks       some   ENG
820       Mujhe shortcut pata hai we will reach quickly       will   ENG
256   Bahar mausam bohot awesome hai let us go for a...     mausam   URD
134         Suno message check karo I sent you the file        you   ENG
323        Mujhe naya phone lena hai suggestion do fast      Mujhe   URD
1093  Kal mera interview scheduled hai preparing ans...     answer   ENG
453   Mera subscription expire ho gaya hai need to r...     expire   ENG
592   Mera exam center bohot door tha reached just i...       door   URD
1130  Unka product design is modern customer loved i...  interface   ENG

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1358 entries, 0 to 1357
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  1358 non-null   object
 1   word      1357 non-null   object
 2   label     1358 non-null   object
dtypes: object(3)
memory usage: 32.0+ KB

In [28]:
print("Dataset loaded successfully!")

Dataset loaded successfully!